name: BaoVeRung
options:
  bundleIdPrefix: com.baoverung.app
packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  MapLibre:
    url: https://github.com/maplibre/maplibre-gl-native-distribution
    from: 6.0.0
targets:
  BaoVeRung:
    type: application
    platform: iOS
    deploymentTarget: "15.5"
    sources:
      - BaoVeRungApp.swift
      - Assets.xcassets
      - Data
      - Repositories
      - Utils
      - Views
      - path: GoogleService-Info.plist
        type: resource
      - path: Data/coordinate_systems.json
        type: resource
    dependencies:
      - package: Firebase
        product: FirebaseDatabase
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseAnalytics
      - package: MapLibre
        product: MapLibre
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_NAME: "BaoVeRung"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGN_IDENTITY: ""
      GENERATE_INFOPLIST_FILE: NO
schemes:
  BaoVeRung:
    build:
      targets:
        BaoVeRung: all
    archive:
      config: Release
